version: "3.0"

services:
  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"

  mysql:
    command:
      --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db